export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'

export const PENDING = 'PENDING'
export const FAILED = 'FAILED'

export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_A_BOOK_SUCCESS = 'FETCH_A_BOOK_SUCCESS'
