export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'

export const FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED'

export const FETCH_A_BOOK_SUCCESS = 'FETCH_A_BOOK_SUCCESS'
